ipc = true
splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/alex/doc/wallpapers/eva.jpg
}

wallpaper {
    monitor = DP-2
    path = /home/alex/doc/wallpapers/eva.jpg
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/alex/doc/wallpapers/eva.jpg
}

