## Catppuccin Latte 改 — 亮色系（优化透明度对比度）

foreground              #2C2E3A
background              #C8CCD6
selection_foreground    #EFF1F5
selection_background    #DC8A78

cursor                  #DC8A78
cursor_text_color       #EFF1F5

url_color               #1A55D0

active_border_color     #8839EF
inactive_border_color   #9CA0B0
bell_border_color       #E64553

active_tab_foreground   #EFF1F5
active_tab_background   #8839EF
inactive_tab_foreground #6C6F85
inactive_tab_background #CCD0DA
tab_bar_background      #DCE0E8

mark1_foreground #EFF1F5
mark1_background #1A55D0
mark2_foreground #EFF1F5
mark2_background #8839EF
mark3_foreground #EFF1F5
mark3_background #209FB5

color0 #4C4F69
color8 #5C5F77
color1 #C01030
color9 #C01030
color2  #2D8220
color10 #2D8220
color3  #C87A10
color11 #C87A10
color4  #1A55D0
color12 #1A55D0
color5  #D060B0
color13 #D060B0
color6  #0D6B70
color14 #0D6B70
color7  #9094A8
color15 #A0A4B8